name: tradingbot
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas>=2.2
  - scipy=1.13.1
  - catboost=1.2.5
  - xgboost>=2.1
  - ccxt=4.4.90
  - pip
  - pip:
      - git+https://github.com/rdv0011/lumibot.git@fix/binance-limit-assets-asset-symbol
      - pandas_market_calendars @ git+https://github.com/rsheftel/pandas_market_calendars.git