name: tradingbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.3.3
  - numpy=2.3.4
  - matplotlib=3.10.3
  - matplotlib-inline=0.1.7
  - tqdm=4.67.1
  - psutil=7.0.0
  - xgboost=3.0.5
  - catboost=1.2.8
  - python-binance=1.0.33
